version: '3.5'

services:
    exploit:
        image: tleemcjr/metasploitable2
        tty: true
        container_name: exploit
        ports:
            - "30445:445"       # SMB
            - "3021:21"         # FTP
            - "3022:22"         # SSH
            - "3023:23"         # Telnet
            - "3080:80"         # HTTP
            - "3443:443"       # HTTPS
            - "35432:5432"     # PostgreSQL
            - "35900:5900"     # VNC
            - "36667:6667"     # IRC
            - "3308:3306"     # mariadb
        volumes:
            - ./:/home/gustavo
        networks:
            kali-app-network:
                ipv4_address: 172.20.0.6
    
    ubuntu:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        container_name: ubuntu
        ports:
            - 8080:80
            - "67:67/udp"
            - 2068:68
            - 2021:21
            - 3307:3306
        volumes:
            - ./:/var/www/html
        cap_add:
            - NET_ADMIN
        networks:
            kali-app-network:
                ipv4_address: 172.20.0.3
    
    parrot:
        build:
            context: .
            dockerfile: parrot.dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - 81:81
        cap_add:
            - NET_ADMIN
        container_name: parrot
        networks:
            kali-app-network:
                ipv4_address: 172.20.0.4
    
    mongo:
        image: mongo:latest
        restart: always
        container_name: mongo
        ports:
            - 27031:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - ./:/var/www/html
        networks:
            kali-app-network:
                ipv4_address: 172.20.0.13

networks:
  kali-app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"  # Changed to a more standard Docker subnet