version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        container_name: kalinginx
        networks:
            - kali-app-network

    kali:
        build:
            context: .
            dockerfile: kali.dockerfile
        volumes:
            - ./:/var/www/html
        container_name: kali
        networks:
            - kali-app-network

networks:
    kali-app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"