version: '3'

services:
    parrot:
        build:
            context: .
            dockerfile: parrot.dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - 80:80
        container_name: parrot
        network_mode: "host"
        # networks:
        #     hack-app-network:
        #         ipv4_address: 17.0.0.3

    # kali:
    #     build:
    #         context: .
    #         dockerfile: kali.dockerfile
    #     volumes:
    #         - ./:/var/www/html
    #     container_name: kali
    #     networks:
    #         hack-app-network:
    #             ipv4_address: 17.0.0.8

    # arch:
    #     build:
    #         context: .
    #         dockerfile: arch.dockerfile
    #     container_name: arch
    #     ports:
    #         - 81:81
    #     volumes:
    #         - ./:/var/www/html
    #     networks:
    #         hack-app-network:
    #             ipv4_address: 17.0.0.8
    
    # ubuntu:
    #     build:
    #         context: .
    #         dockerfile: ubuntu.dockerfile
    #     container_name: ubuntu
    #     ports:
    #         - 8800:8880
    #     volumes:
    #         - ./:/var/www/html
    #     networks:
    #         hack-app-network:
    #             ipv4_address: 17.0.0.9

# networks:
#     hack-app-network:
#         driver: bridge
#         ipam:
#             driver: default
#             config:
#                 - subnet: "17.0.0.0/16"